{% set name = "kwant" %}
{% set version = "1.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://antonakhmerov.org/misc/kwant-1.4.1.dev20+g40838439.tar.gz
  sha256: e06cd7c2a0b97f7001d4a01a57b1fb1847587c0a29ef67365db47863eb9118b0
  patches:
    - skip_tests.patch  # [win]
    - skip_test_basis_ordering.patch
    - qsymm.patch  # backport https://gitlab.kwant-project.org/kwant/kwant/merge_requests/318

build:
  skip: true  # [py2k]
  number: 2

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - cython
    - mumps-seq  # [not win]
    - numpy
    - scipy
    - pytest =4.6.4
    - tinyarray
  run:
    - python
    - mumps-seq  # [not win]
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - scipy
    - pytest =4.6.4
    - tinyarray
    - sympy
    - qsymm
    - vc 14  # [win and py>=35]

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests
  commands:
    - conda inspect linkages -p $PREFIX kwant  # [not win]
    - conda inspect objects -p $PREFIX kwant  # [osx]

about:
  home: http://kwant-project.org/
  license: BSD 2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Package for numerical quantum transport calculations.'
  description: |
    Kwant is a free (open source) Python package for numerical calculations on
    tight-binding models with a strong focus on quantum transport. It is designed to
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant
    is often faster than other available codes, even those entirely written in the
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
    - jbweston
    - akhmerov
