{% set name = "kwant" %}
{% set version = "1.3.3" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://downloads.kwant-project.org/kwant/kwant-{{ version }}.tar.gz
  sha256: 9f3274beddaa2a6951dda85a5cf6597d7a191d56d50753f53ee790509a1bc218

build:
  skip: true  # [win or py2k]
  number: 2
  features:
    - blas_{{ variant }}

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - blas 1.1 {{ variant }}
    - openblas
    - mumps
    - numpy  # [py27]
    - numpy  # [py35]
    - numpy  # [py36]
    - scipy
    - pytest
    - tinyarray

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas
    - mumps
    - {{ pin_compatible('numpy') }}  # [py27]
    - {{ pin_compatible('numpy') }}  # [py35]
    - {{ pin_compatible('numpy') }}  # [py36]
    - matplotlib
    - scipy
    - pytest
    - tinyarray
    - sympy

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests
  commands:
    - conda inspect linkages -p $PREFIX kwant  # [not win]
    - conda inspect objects -p $PREFIX kwant  # [osx]

about:
  home: http://kwant-project.org/
  license: BSD 2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Package for numerical quantum transport calculations.'
  description: |
    Kwant is a free (open source) Python package for numerical calculations on
    tight-binding models with a strong focus on quantum transport. It is designed to
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant
    is often faster than other available codes, even those entirely written in the
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
    - jbweston
