{% set name = "kwant" %}
{% set version = "1.5.0" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://test.pypi.io/packages/source/{{ name[0] }}/{{ name }}/kwant-{{ version }}.tar.gz
  sha256: a41e7b316f058c633dd22e02993d43e164e0a4d08a6afeec0224b587790d046b
  patches:
    - raise_tolerance.patch  # [win]
    # - skip_tests.patch  # [win]
    # - skip_test_basis_ordering.patch
    # - skip_test_kpm_kwant_op.patch  # [win]
    # - schur-test.patch  # [osx]

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  number: {{ build }}
  string: py{{ py }}h{{ PKG_HASH }}_{{ build }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - libblas
    - libcblas
    - python
    - cython
    - python-mumps
    - numpy
    - scipy
    - pytest
    - tinyarray
  run:
    - python
    - python-mumps
    - {{ pin_compatible('numpy') }}
    - matplotlib-base
    - scipy
    - pytest
    - tinyarray
    - sympy
    - qsymm
    - vc 14  # [win and py>=35]

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests

about:
  home: http://kwant-project.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Package for numerical quantum transport calculations.
  description: |
    Kwant is a free (open source) Python package for numerical calculations on
    tight-binding models with a strong focus on quantum transport. It is designed to
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant
    is often faster than other available codes, even those entirely written in the
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
    - jbweston
    - akhmerov
