{% set name = "kwant" %}
{% set version = "1.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kwant-{{ version }}.tar.gz
  sha256: 994b0a3848f78002ef8e3d60f36b9dfab719ee58c5189fc902a7acd0dec2cfbb
  patches:
    - skip_tests.patch  # [win]
    - skip_test_basis_ordering.patch
    - skip_test_kpm_kwant_op.patch  # [win]

build:
  skip: true  # [py2k]
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - cython
    - mumps-seq  # [not win]
    - numpy
    - scipy
    - pytest =4.6.4
    - tinyarray
  run:
    - python
    - mumps-seq  # [not win]
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - scipy
    - pytest =4.6.4
    - tinyarray
    - sympy
    - qsymm
    - vc 14  # [win and py>=35]

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests
  commands:
    - conda inspect linkages -p $PREFIX kwant  # [not win]
    - conda inspect objects -p $PREFIX kwant  # [osx]

about:
  home: http://kwant-project.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Package for numerical quantum transport calculations.'
  description: |
    Kwant is a free (open source) Python package for numerical calculations on
    tight-binding models with a strong focus on quantum transport. It is designed to
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant
    is often faster than other available codes, even those entirely written in the
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
    - jbweston
    - akhmerov
