{% set name = "kwant" %}
{% set version = "1.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://downloads.kwant-project.org/kwant/kwant-{{ version }}.tar.gz
  sha256: 8c0ccf341dfa74e1d69f1508968c4d4e9fb36f74685f101897df6a84ed7043df
  patches:
    - skip_tests.patch  # [win]
    - skip_test_basis_ordering.patch

build:
  skip: true  # [py2k]
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - python
    - cython
    - mumps-seq  # [not win]
    - numpy 1.11
    - scipy
    - pytest
    - tinyarray
  run:
    - python
    - mumps-seq  # [not win]
    - {{ pin_compatible('numpy') }}
    - matplotlib
    - scipy
    - pytest
    - tinyarray
    - sympy
    - qsymm    
    - vc 14  # [win and py>=35]

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests
  commands:
    - conda inspect linkages -p $PREFIX kwant  # [not win]
    - conda inspect objects -p $PREFIX kwant  # [osx]

about:
  home: http://kwant-project.org/
  license: BSD 2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Package for numerical quantum transport calculations.'
  description: |
    Kwant is a free (open source) Python package for numerical calculations on
    tight-binding models with a strong focus on quantum transport. It is designed to
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant
    is often faster than other available codes, even those entirely written in the
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
    - jbweston
    - akhmerov
