{% set name = "kwant" %}
{% set version = "1.4.2" %}
{% set build = 5 %}
{% set mpi = "mpich" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kwant-{{ version }}.tar.gz
  sha256: 994b0a3848f78002ef8e3d60f36b9dfab719ee58c5189fc902a7acd0dec2cfbb
  patches:
    - skip_tests.patch  # [win]
    - skip_test_basis_ordering.patch
    - skip_test_kpm_kwant_op.patch  # [win]
    - init_mpi.patch  # [mpi != "nompi"]

# We set the build number of the `nompi` variant higher than
# the `mpi` variant, such that the `nompi` will be preferred.
{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}

build:
  skip: true  # [py2k]
  number: {{ build }}
  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*  # [mpi != "nompi"]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - libblas
    - libcblas
    - python
    - cython
    - mumps-seq  # [not win and mpi == "nompi"]
    - mumps-mpi  # [mpi != "nompi"]
    - {{ mpi }}   # [mpi != "nompi"]
    - mpi4py  # [mpi != "nompi"]
    - numpy
    - scipy
    - pytest
    - tinyarray
  run:
    - python
    - mumps-seq  # [not win and mpi == "nompi"]
    - mumps-mpi  # [mpi != "nompi"]
    - {{ mpi }}  # [mpi != "nompi"]
    - mpi4py  # [mpi != "nompi"]
    - {{ pin_compatible('numpy') }}
    - matplotlib-base <3.4  # Unpin in >1.4.2
    - scipy
    - pytest
    - tinyarray
    - sympy <1.7  # Unpin in >1.4.2
    - qsymm
    - vc 14  # [win and py>=35]

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests
  commands:
    - conda inspect linkages -p $PREFIX kwant  # [not win]
    - conda inspect objects -p $PREFIX kwant  # [osx]

about:
  home: http://kwant-project.org/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: Package for numerical quantum transport calculations.
  description: |
    Kwant is a free (open source) Python package for numerical calculations on
    tight-binding models with a strong focus on quantum transport. It is designed to
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant
    is often faster than other available codes, even those entirely written in the
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
    - jbweston
    - akhmerov
