{% set name = "kwant" %}
{% set version = "1.3.0" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: kwant-1.4.0a0.dev20+gf4e8a3c.tar.gz
  url: https://joseph.weston.site/uploads/kwant-1.4.0a0.dev20+gf4e8a3c.tar.gz
  sha256: e589d0ef43225e1afdd8e34b2564f5f4a14f07440703dac037aac576b2cd3449

build:
  skip: true  # [py2k]
  number: 202
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - toolchain
    - cython
    - gcc  # [osx]
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - mumps  # [not win]
    - numpy 1.7.*  # [py27]
    - numpy 1.9.*  # [py35]
    - numpy 1.11.*  # [py36]
    - scipy
    - pytest
    - tinyarray
    - libgfortran  # [linux]

  run:
    - python
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.19|0.2.19.*  # [not win]
    - mumps  # [not win]
    - numpy >=1.7  # [py27]
    - numpy >=1.9  # [py35]
    - numpy >=1.11  # [py36]
    - matplotlib
    - scipy
    - pytest
    - tinyarray
    - libgfortran  # [not win]
    - sympy

test:
  imports:
    - kwant
    - kwant.graph
    - kwant.graph.tests
    - kwant.linalg
    - kwant.linalg.tests
    - kwant.physics
    - kwant.physics.tests
    - kwant.solvers
    - kwant.solvers.tests
    - kwant.tests
  commands:
    - conda inspect linkages -p $PREFIX kwant  # [not win]
    - conda inspect objects -p $PREFIX kwant  # [osx]

about:
  home: http://kwant-project.org/
  license: BSD 2-Clause
  license_file: LICENSE.rst
  license_family: BSD
  summary: 'Package for numerical quantum transport calculations.'
  description: |
    Kwant is a free (open source) Python package for numerical calculations on
    tight-binding models with a strong focus on quantum transport. It is designed to
    be flexible and easy to use. Thanks to the use of innovative algorithms, Kwant
    is often faster than other available codes, even those entirely written in the
    low level FORTRAN and C/C++ languages.
  doc_url: https://kwant-project.org/doc/1/
  dev_url: https://gitlab.kwant-project.org/kwant/kwant/

extra:
  recipe-maintainers:
    - basnijholt
