# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GF84RU3CEwagbJ7SFTx9vEQm7NphWyuGCR5JEjd+B4dv4c1iHheyHKQk44v4iIVjmDCRCOj0zrzikS4al/x7ksRSfMMdYHR39CIWHEIEHvAgbf7/ZmvChPD4HeqNNp3ib8GXJku57HoOe/mF5enqMh2tiNXdE0f4fWXiU1fsqDrIufqrqVKAoC3F/soUxhfaMUXbwfLdDHFjRgefjQ1mAaCfXyAimmnh5qEt4EyGzlt0MlgmL3Gocuev1ECvPZE6kaNpVOslZISoT30CdptqYTmOIOdAttrhHdGteFh5XK718se29TeEpeYo5+ahcJw4nYhHeUQnueYaMz+KsuMOUjEagL/6NcmhdF0v5n+GI4/8hftTbfcgklxHbz0PlvFV8IQbatbpoD6Z8koGms8AWZuSg59fQ4bzPOpDPFQPgJDkmFevbALqC1swLMsTFvTuD3/Mih0FfyCSZYNTYz0MQtOjmalB0p35McQWjT9jpsYE0K52lCLFoHDhiUWqlF5Xo7JZmKO7uJyfU6fq3Vw3J13ZwKDNwXO4Em1clt1c2oMhFQaDDSx78aKwJ8hcQXwRcGnSpPGW5ffwyc5L37kJ4DPHY47Q6/lTa5NNASLOoQ8Dq+8oKUeiHNwakYeZgcKoOpxvVBDGujoTEAUXQnbOGTGDHFc2hMmBJvkeG5b3Fp4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
