travis:
  secure:
    BINSTAR_TOKEN: n8rWGw5kcIrHvxhV63Ltj6JiBXflkZkePOtJgvj2jTB2qFUgKmw3y3n7yOj15v4aSMOisE+Ogb8lM2NXjgwIn52D8K2hNViHWUqlej+BUGtj/1TJaS56mmOXadUd8eO0PhJP65CsVYTvBNpH86V2NEZNjKSbcevWGU/Yz9GO+CVmcG7RZFdYwFxfE6f1BegF1I5ylSq+5/vsxXfNw6THV/aTa2WrhmaIAN1w7UPktwzHxWKsbL1hAC4CpXh/3tzap1Fr84u0J/IUMQaD3fzUHJOhrSjA5TboXq63IX84UUbaQZXugjT1j+A5qjGkbXRPTCjXrnGDC2hvXpqFqLgvRbLvKvlpJCNaQXTf7d5n8hVDEyoz8sev5RSvUomPUYoxl5RHL+fQ5h5C3L/ZFvM31R6aLpL6VzPV9Y2X6LSNbkdxqo5G4z4UrA5ns6YQdSyqYL7TekGMEb9Nq14a1jFAk/HI+7HC49UZUyQc3wWcFE5eyaCyqp60YVSNnGC6a9Z1u3kEuClKI5tS9F+FHHcv03h3N6EpY6/svzxaw1JPWyBlnjqRBzG9NGpoKBWeKqHs3ls0hEPWlBY2UmiIn7nYRd/RQnNebQ6+VRx02xEU3jbI6Qybhm2q0Kuxgwl/snC6jRfeuC0lDfc4kfUPjVacQtU65Z4hM8VKVqPgy2GNNv8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
